theme_agus <- function(fuente="Open Sans",
                       tamaniodeletra=20,
                       leyenda="bottom",
                       angulo=0) {
  theme(
    text =  element_text(color="black",
                         family = fuente,
                         size=tamaniodeletra),
    axis.text.x = element_text(color="black",
                               family = fuente,
                               margin=ggplot2::margin(5, b = 10),
                               angle = angulo),
    axis.text.y = element_text(color="black",
                               family = fuente),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_blank(),
    panel.background = element_blank(),
    panel.grid.major.y = element_line(color="gray93"),
    legend.position = leyenda,
    plot.subtitle = element_text(size=rel(22/28),
                                 margin=ggplot2::margin(3,0,3,0)),
    plot.title.position = "plot",
    plot.title = element_text(size=rel(1),
                              face="bold",
                              color="#222222"),
    axis.title.y = element_text(vjust = 3),
    legend.background = element_blank(),
    legend.box.background = element_blank(),
    legend.key = element_blank(),
    axis.line.x = element_line(color="black"),
    axis.ticks = ggplot2::element_blank(),
    legend.text = element_text(family = fuente,
                               size=rel(22/28)),
    strip.background = ggplot2::element_rect(fill="white"),
    strip.text = ggplot2::element_text(size  = rel(23/28),  hjust = 0),
    plot.caption = element_text(face="italic",
                                hjust=0.5)
  )
}